In [7]:
import numpy as np

# Create a simple array
my_array = np.arange(10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
list = [3.14, 2.17, 0, 1, 2]
my_array = np.array(list)
print(my_array)

[3.14 2.17 0.   1.   2.  ]


In [10]:
my_array = np.arange(1, 10).reshape(3, 3)
print(my_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
my_array = np.random.rand(4, 5)
my_array = np.round(my_array, 2)
print(my_array)

[[0.49 0.09 0.27 0.85 0.77]
 [0.37 0.59 0.6  0.45 0.63]
 [0.43 0.22 0.56 0.11 0.53]
 [0.58 0.2  0.33 0.32 0.15]]


In [ ]:
my_array = np.array([[21, 22, 23, 22, 22], 
                     [20, 21, 22, 23, 24], 
                     [21, 22, 23, 22, 22]])
s_row = my_array[1]
print(s_row)

[20 21 22 23 24]


In [ ]:
my_array = np.arange(10)
reversed_my_array = my_array[::-1]
print(reversed_my_array)

[9 8 7 6 5 4 3 2 1 0]


In [ ]:
# identity_matrix = np.eye(4) 
identity_matrix = np.identity(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
my_array = np.arange(10)
sum_v = np.sum(my_array)
average_v = np.mean(my_array)
print(f"Sum: {sum_v}, Average: {average_v}")

Sum: 45, Average: 4.5


In [ ]:
my_array = np.arange(1, 21)
reshaped_my_array = my_array.reshape(4, 5)
print(reshaped_my_array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [ ]:
my_array = np.arange(10)
odd_num = my_array[my_array % 2 != 0]
print(odd_num)

[1 3 5 7 9]
