In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
print(np.__version__)

1.21.6


In [3]:
import numpy as np

# Create a simple array
my_array = np.array([1, 2, 3, 4, 5])
print(my_array)

[1 2 3 4 5]


In [9]:
my_array = np.array([1,2,3,4,5,6]).reshape(2,3)
print(my_array)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
array_1 = np.array([1, 2, 3, 4])
print("1D Array:", array_1)


array_2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array_2)

print("Shape:", array_2.shape)  # Expected Output: Shape: (2, 3) - 2 rows and 3 columns
print("Size:", array_2.size)   # Expected Output: Size: 6 - Total 6 elements
print("Data Type:", array_2.dtype)  # Expected Output: Data Type: int64 (or similar, depending on system)

1D Array: [1 2 3 4]
2D Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Size: 6
Data Type: int32


In [14]:
array_1 = np.array([1, 2, 3, 4])
print("1D Array:", array_1)
array_2 = np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3)
print(f"{array_1.shape}, {array_1.size}, {array_1.dtype}")
print(f"{array_2.shape}, {array_2.size}, {array_2.dtype}")

array_float = np.arange(1, 4, dtype=float)
dtype_float = array_float.dtype
print(array_float)
print(array_float.dtype)


1D Array: [1 2 3 4]
(4,), 4, int32
(2, 3), 6, int32
[1. 2. 3.]
float64


In [17]:

temp = np.array([20, 23, 19, 18, 20, 21, 25])
array_2 = np.arange(1,11).reshape(2,5)
print(array_2)

array_3 = np.array([[[255, 0, 128], [30, 200, 50], [100, 150, 200]], 
                    [[75, 180, 90], [220, 110, 60], [45, 130, 190]],
                    [[15, 230, 85], [160, 95, 240], [20, 140, 210]]])
print(array_3)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[[255   0 128]
  [ 30 200  50]
  [100 150 200]]

 [[ 75 180  90]
  [220 110  60]
  [ 45 130 190]]

 [[ 15 230  85]
  [160  95 240]
  [ 20 140 210]]]


In [49]:
arr = np.arange(0,10)
print(arr[5])
print(arr[2:8])
arr2 = np.random.randint(10,51,6)
print(arr2)
print(arr2[arr2>30])
print(arr2[[1,3,5]])



5
[2 3 4 5 6 7]
[44 39 44 43 35 16]
[44 39 44 43 35]
[39 43 16]


In [18]:
import numpy as np

# Example 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Accessing a single element
print("Element at row 1, column 2:", array_2d[1, 2])  # Output: 6

# Accessing a row
print("Second row:", array_2d[1, :])  # Output: [4 5 6]

# Accessing a column
print("Third column:", array_2d[:, 2])  # Output: [3 6 9]

Element at row 1, column 2: 6
Second row: [4 5 6]
Third column: [3 6 9]


In [19]:
import numpy as np

# Example 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Slicing a portion of the array
print("Slice of the array:", array_2d[0:2, 1:3])  # Output: [[2 3] [5 6]]

Slice of the array: [[2 3]
 [5 6]]


In [22]:
import numpy as np

# Example array
array = np.array([[1, 2], [3, 4], [5, 6]])

# Boolean indexing
result = array[array > 3]
print("Result of Boolean Indexing:", result)  # Output: [4 5 6], a 1D array

Result of Boolean Indexing: [4 5 6]


In [24]:
import numpy as np

# Creating a sample array
array = np.array([10, 20, 30, 40, 50])

# Indexing (accessing a single element)
print("First element:", array[0])

# Slicing (accessing multiple elements)
print("First three elements:", array[:3])

# Boolean indexing
print("Elements greater than 25:", array[array > 25])

# Fancy indexing (using a list of indices)
print("Select specific elements:", array[[1, 3]])

First element: 10
First three elements: [10 20 30]
Elements greater than 25: [30 40 50]
Select specific elements: [20 40]


In [25]:
rand = np.random.randint(10, 50, 6)
print(rand[rand>30])

[36 38 43 44]


In [26]:
x = np.array([1, 2, 3, 4, 5, 6, 7])
new = np.random.permutation(x)
new

array([1, 3, 6, 5, 4, 7, 2])

In [27]:
two = np.array([[1,2], [3,4], [5,6]])
np.random.permutation(two)

array([[3, 4],
       [5, 6],
       [1, 2]])

In [32]:
arr = np.array([1, 2, 3, 4, 5])
arr[2] = 10  # Changing the third element
print(arr)  # Output: [1, 2, 10, 4, 5]
arr[1:4] = [20, 30, 40]
print(arr)  # Output: [1, 20, 30, 40, 5]
arr[arr > 10] = 100
print(arr)  # Output: [1, 100, 100, 100, 5]
arr[np.array([1, 3])] = 500
print(arr)  # Output: [1, 500, 100, 500, 5]
sub_arr = arr[1:3]
sub_arr[0] = 600
print(arr)  # Output: [1, 600, 100, 500, 5]

[ 1  2 10  4  5]
[ 1 20 30 40  5]
[  1 100 100 100   5]
[  1 500 100 500   5]
[  1 600 100 500   5]


In [50]:
import numpy as np

# Creating sample arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise addition
print("Addition:", a + b)

# Broadcasting
print("Broadcasting with scalar:", a * 3)

Addition: [5 7 9]
Broadcasting with scalar: [3 6 9]


In [51]:
import numpy as np

# Creating a 1D array
a = np.array([1, 2, 3])

# Adding a scalar value to the array
result = a + 5

print("Original Array:", a)
print("After Adding 5:", result)

Original Array: [1 2 3]
After Adding 5: [6 7 8]


In [52]:
import numpy as np

# Creating a 1D array and a 2D array
a = np.array([0, 1, 2])
b = np.array([[0, 1, 2], [3, 4, 5]])

# Adding the 1D array to each row of the 2D array
result = a + b

print("1D Array:", a)
print("2D Array:", b)
print("Broadcasted Addition:", result)

1D Array: [0 1 2]
2D Array: [[0 1 2]
 [3 4 5]]
Broadcasted Addition: [[0 2 4]
 [3 5 7]]


In [53]:
import numpy as np

# Creating two arrays
a = np.array([[1], [2], [3]])
b = np.array([1, 2, 3])

# Adding the two arrays
result = a + b

print("Array a:", a)
print("Array b:", b)
print("Broadcasted Addition:", result)

Array a: [[1]
 [2]
 [3]]
Array b: [1 2 3]
Broadcasted Addition: [[2 3 4]
 [3 4 5]
 [4 5 6]]


In [54]:
import numpy as np

# Creating two incompatible arrays
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2])

try:
    result = a + b
except ValueError as e:
    print("Error:", e)

Error: operands could not be broadcast together with shapes (2,3) (2,) 


In [56]:
import numpy as np

# Creating a 2D array and a 1D array
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2, 3])

# Element-wise multiplication
result = a * b

print("2D Array:", a)
print("1D Array:", b)
print("Broadcasted Multiplication:", result)

2D Array: [[1 2 3]
 [4 5 6]]
1D Array: [1 2 3]
Broadcasted Multiplication: [[ 1  4  9]
 [ 4 10 18]]


In [57]:
# Creating a sample array
array = np.array([[1, 2, 3], [4, 5, 6]])

# Sum of all elements
print("Sum:", np.sum(array))

# Mean value
print("Mean:", np.mean(array))

# Minimum and Maximum
print("Min:", np.min(array), "Max:", np.max(array))

Sum: 21
Mean: 3.5
Min: 1 Max: 6


In [60]:
# Transposing for matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([5, 6])
product = A.dot(B.transpose())  # Transposing B to make multiplication possible
print(product)

[17 39]


In [94]:
a=np.arange(12).reshape(4,3)
print(a)
b=a.reshape(2,6)
print(b)
c=b.T
print(c)
d=np.arange(12).reshape(4,3)
e=d.T
f=e.reshape(-1)
print(f)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]
[ 0  3  6  9  1  4  7 10  2  5  8 11]


In [89]:
# Reshaping data for time-series analysis
time_series_data = np.random.rand(364)  # Daily data for a year
reshaped_for_analysis = time_series_data.reshape(52, 7)  # Weekly data, 7 days a week
print(reshaped_for_analysis)

[[0.1583596  0.43950998 0.55363387 0.1468714  0.1507317  0.35877406
  0.10078998]
 [0.09211218 0.33695886 0.15356701 0.90084859 0.78185883 0.78737568
  0.32506927]
 [0.36692893 0.03940257 0.16634402 0.6426909  0.01176864 0.27350513
  0.85067729]
 [0.00207711 0.26060525 0.79766036 0.91454643 0.8200808  0.24152564
  0.71570317]
 [0.8523483  0.06743114 0.14186367 0.28723553 0.18015641 0.82963314
  0.26781749]
 [0.46113428 0.25151186 0.34816995 0.63170684 0.9589562  0.515122
  0.51438443]
 [0.1855366  0.71232343 0.15351775 0.90642855 0.56605032 0.06266672
  0.72263754]
 [0.59676023 0.03882226 0.36908257 0.33669353 0.06424504 0.99600151
  0.28558942]
 [0.28109505 0.67620217 0.04470024 0.85062024 0.4183726  0.28386575
  0.59365908]
 [0.73588211 0.812215   0.2313995  0.92620144 0.46847621 0.90475878
  0.23891204]
 [0.47119046 0.73515084 0.74941821 0.97958895 0.10274748 0.8252567
  0.19756791]
 [0.45821031 0.10369958 0.84679815 0.44684072 0.03459864 0.30194262
  0.55658393]
 [0.49463518 0.6753