In [1]:
import numpy as np

# Creating a matrix
matrix_A = np.array([[1, 2], [3, 4]])
print("Matrix A:\n", matrix_A)

# Reshaping a matrix
reshaped_matrix = np.reshape(matrix_A, (4, 1))
print("Reshaped Matrix:\n", reshaped_matrix)

# Changing values in a matrix
matrix_A[0, 0] = 5
print("Updated Matrix A:\n", matrix_A)

Matrix A:
 [[1 2]
 [3 4]]
Reshaped Matrix:
 [[1]
 [2]
 [3]
 [4]]
Updated Matrix A:
 [[5 2]
 [3 4]]


In [2]:
import numpy as np

# Example survey data matrix (5 respondents, 4 questions)
survey_data = np.array([[5, 1, 4, 4],
                        [4, 2, 4, 3],
                        [5, 1, 1, 5],
                        [3, 2, 1, 2],
                        [2, 1, 2, 5]])

# Calculating various statistics
average_responses = np.mean(survey_data, axis=0)
total_responses = np.sum(survey_data, axis=0)
max_responses = np.max(survey_data, axis=0)
min_responses = np.min(survey_data, axis=0)

print("Average Responses:", average_responses)
print("Total Responses:", total_responses)
print("Maximum Responses:", max_responses)
print("Minimum Responses:", min_responses)

Average Responses: [3.8 1.4 2.4 3.8]
Total Responses: [19  7 12 19]
Maximum Responses: [5 2 4 5]
Minimum Responses: [2 1 1 2]


In [6]:
import numpy as np

movie_ratings = np.array([
    [5, 1, 4],
    [4, 4, 2],
    [4, 3, 5],
    [1, 1, 5],
    [3, 2, 1]
])

average_ratings = np.mean(movie_ratings, axis=0)
viewer_preferences = np.argmax(movie_ratings, axis=1) + 1 

print(average_ratings)
print(viewer_preferences)


[3.4 2.2 3.4]
[1 1 3 3 1]


In [7]:
import numpy as np

# Create two 3x3 matrices
matrix_a = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

matrix_b = np.array([[9, 8, 7],
                     [6, 5, 4],
                     [3, 2, 1]])

# Perform addition
addition_result = np.add(matrix_a, matrix_b)

# Perform subtraction
subtraction_result = np.subtract(matrix_a, matrix_b)

# Display the results
print("Matrix A:\n", matrix_a)
print("Matrix B:\n", matrix_b)
print("Addition Result:\n", addition_result)
print("Subtraction Result:\n", subtraction_result)

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
Addition Result:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Subtraction Result:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [8]:
import numpy as np

# Temperature data matrix (4 cities, 7 days)
temperature_data = np.array([
    [27, 20, 15, 18, 26, 18, 22],
    [24, 18, 20, 17, 19, 22, 21],
    [23, 23, 27, 25, 16, 21, 22],
    [22, 29, 23, 16, 20, 24, 28]
])

# Task 1: Calculate average temperature for each city
average_temperatures = np.mean(temperature_data, axis=1)

# Task 2: Find the highest and lowest temperatures in each city
max_temperatures = np.max(temperature_data, axis=1)
min_temperatures = np.min(temperature_data, axis=1)

# Task 3: Compare temperatures on the first and last day of the week
day_comparison = temperature_data[:, 6] - temperature_data[:, 0]

# Display the results
print("Average Temperature for Each City:\n", average_temperatures)
print("Maximum Temperature for Each City:\n", max_temperatures)
print("Minimum Temperature for Each City:\n", min_temperatures)
print("Temperature Difference between Day 1 and Day 7 for Each City:\n", day_comparison)

Average Temperature for Each City:
 [20.85714286 20.14285714 22.42857143 23.14285714]
Maximum Temperature for Each City:
 [27 24 27 29]
Minimum Temperature for Each City:
 [15 17 16 16]
Temperature Difference between Day 1 and Day 7 for Each City:
 [-5 -3 -1  6]


In [9]:
import numpy as np
import matplotlib.pyplot as plt

# Generate a normal distribution
mean = 0
std_dev = 1
samples = np.random.normal(mean, std_dev, 1000)

# Plotting the distribution
plt.hist(samples, bins=30, density=True)
plt.title("Normal Distribution")
plt.xlabel("Value")
plt.ylabel("Frequency")
plt.show()

<Figure size 640x480 with 1 Axes>

In [10]:
import numpy as np
from scipy.stats import skew, kurtosis

# Generate a random dataset
np.random.seed(0)  # For reproducibility
dataset = np.random.randint(0, 100, size=100)

# Task 1: Random Sampling and Shuffling
sampled_data = np.random.choice(dataset, size=20, replace=False)
shuffled_data = np.random.permutation(sampled_data)

# Task 2: Compute Descriptive Statistics
mean_value = np.mean(dataset)
median_value = np.median(dataset)
variance_value = np.var(dataset)
skewness_value = skew(dataset)
kurtosis_value = kurtosis(dataset)

# Display the results
print("Original Dataset:", dataset)
print("Sampled Data:", sampled_data)
print("Shuffled Data:", shuffled_data)
print("Mean:", mean_value)
print("Median:", median_value)
print("Variance:", variance_value)
print("Skewness:", skewness_value)
print("Kurtosis:", kurtosis_value)

Original Dataset: [44 47 64 67 67  9 83 21 36 87 70 88 88 12 58 65 39 87 46 88 81 37 25 77
 72  9 20 80 69 79 47 64 82 99 88 49 29 19 19 14 39 32 65  9 57 32 31 74
 23 35 75 55 28 34  0  0 36 53  5 38 17 79  4 42 58 31  1 65 41 57 35 11
 46 82 91  0 14 99 53 12 42 84 75 68  6 68 47  3 76 52 78 15 20 99 58 23
 79 13 85 48]
Sampled Data: [65 91 79 23 88 11 46 34 87 21  9 83 87 46 12 14 19  1 47  0]
Shuffled Data: [ 0 21 79 88 12 87 65 83 34 11 46 19 46 47  9  1 14 23 87 91]
Mean: 48.23
Median: 47.0
Variance: 796.9371000000001
Skewness: -0.03679365802939353
Kurtosis: -1.1824940022625319
